version: '3.4'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    networks:
      rede1:
        ipv4_address: 172.16.238.3
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d database'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      rede1:
        ipv4_address: 172.16.238.4
    depends_on:
      - db
  api:
    container_name: api_ts
    image: bruno/api_ts
    ports:
      - "3000:3000"
    networks:
      rede1:
        ipv4_address: 172.16.238.5
    depends_on:
      db:
        condition: service_started
      
networks:
  rede1:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.238.0/16

volumes:
  db:
    driver: local